solutions for tasks module 3
js-tasks-ru/jsbasic-20240115_tinaatimkovaa pull request #5
Opened 2024-02-01 02:41 UTC by tinatimkova

2024-02-01 02:42 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2024-02-03 17:42 UTC, SinimaWath requested changes

2024-02-03 17:42 UTC, SinimaWath commented on 3-module/4-task/index.js
> +  .map(({ name, balance }) => [`${name}, ${balance}`])
`[`${name}, ${balance}`]` - А зачем тут массив?

2024-02-03 17:42 UTC, SinimaWath commented on 3-module/3-task/index.js
> +    })
Давай тут используем сокращенную версию стрелочной функции:
`.map((word, index) => word && index > 0 ? word[0].toUpperCase() + word.slice(1) : word )`

2024-02-05 01:32 UTC, tinatimkova commented on 3-module/4-task/index.js
> +  .map(({ name, balance }) => [`${name}, ${balance}`])
это лишнее) я возвращала [ name, balance ], потом добавила кавычки, и не подумала убрать массив. спасибо!

2024-02-05 01:35 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2024-02-05 14:04 UTC, SinimaWath approved these changes

2024-02-05 14:05 UTC, merged